services:
  db:
    image: postgres:18
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'postgres', '-d', 'postgres']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  # Postgres UI
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4
    configs:
      - source: pgadmin-pgpass
        target: /config/pgpass
        uid: '5050'
        gid: '5050'
        mode: 0400
      - source: pgadmin-servers
        target: /pgadmin4/servers.json
        mode: 0444
    depends_on:
      - db
    ports:
      - '8888:80'
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      GUNICORN_ACCESS_LOGFILE: '/dev/null'

  flyway:
    image: flyway/flyway:10
    volumes:
      - ./backend/src/main/resources/db/migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    command: >
      -X
      -url=jdbc:postgresql://db:5432/postgres
      -user=postgres
      -password=password
      migrate

  # To run manual flyway commands
  flyway-manual:
    image: flyway/flyway:10
    container_name: flyway-manual
    profiles: ['manual']
    env_file:
      - backend/.env
    volumes:
      - ./backend/src/main/resources/db/migration:/flyway/sql
    depends_on:
      db:
        condition: service_healthy
    entrypoint: ['flyway']

  y-websocket:
    build:
      context: ./external-services
      dockerfile: yWsDockerfile
    container_name: y-websocket
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
      HOST: y-websocket
      YPERSISTENCE: /persistence
    volumes:
      - yws-data:/persistence

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    depends_on:
      - db
      - flyway
      - frontend
    container_name: backend
    ports:
      - '8080:8080'
      - '5005:5005' # Debug port
    volumes:
      - ./backend:/usr/src/maven
      - maven-repo:/root/.m2
      - /var/run/docker.sock:/var/run/docker.sock
    env_file:
      - .env
    environment:
      SPRING_PROFILES_ACTIVE: dev
      MAVEN_OPTS: >
        -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
      FRONTEND_URL: http://localhost:3000

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: frontend
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/app
    environment:
      NODE_ENV: development
      VITE_BACKEND_URL: http://localhost:8080
      VITE_WS_URL: ws://localhost:8081
    command: ./dev-start.sh

configs:
  pgadmin-servers:
    content: |
      {
        "Servers": {
          "1": {
            "Name": "Local Postgres",
            "Group": "Servers",
            "Host": "db",
            "Port": 5432,
            "MaintenanceDB": "postgres",
            "Username": "postgres",
            "PassFile": "/config/pgpass"
          }
        }
      }
  pgadmin-pgpass:
    content: |
      db:5432:*:postgres:password

volumes:
  maven-repo:
  postgres_data:
  yws-data:
