package csd.t6.backend.config;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.context.annotation.Profile;
import org.springframework.context.event.ContextRefreshedEvent;
import org.springframework.context.event.EventListener;
import org.springframework.stereotype.Component;

// Hooks onto dev reload
// Automatically generates schema typings for FE
@Component
@Profile("dev")
public class ReloadHook {
  private static final Logger log = LoggerFactory.getLogger(ReloadHook.class);

  @EventListener
  public void onContextRefreshed(ContextRefreshedEvent event) {
    runCliCommand();
  }

  private void runCliCommand() {
    try {
      ProcessBuilder pb = new ProcessBuilder(
          "docker", "exec", "-t",
          "frontend",
          "npm", "run", "generate-api");

      pb.inheritIO();

      Process process = pb.start();
      int exitCode = process.waitFor();

      if (exitCode == 0) {
        log.info("API files successfully generated by npm script.");
      } else {
        log.warn("npm run generate-api finished with non-zero exit code: {}", exitCode);
      }

    } catch (Exception e) {
      log.error("Failed to run npm generate-api script", e);
    }
  }
}
