export const RELATIONS = {
  Brainrot: [
    'Brainrot animals',
    'Skibidi toilet',
    'Slang',
    'What the Sigma?',
    '67',
  ],
  'Brainrot animals': ['Brainrot', 'Skibidi toilet', 'Slang'],
  '67': ['Brainrot', 'Slang'],
  'Skibidi toilet': [
    'Brainrot',
    'Brainrot animals',
    'What the Sigma?',
    'Slang',
  ],
  Chuzz: ['Huzz', 'Fuzz', 'Slang'],
  Huzz: ['Chuzz', 'Fuzz', 'Slang'],
  Fuzz: ['Chuzz', 'Huzz', 'Slang'],
  Sigma: ['What the Sigma?', 'Aura', 'Mogging', 'Slang'],
  'Fanum tax': ['Rizz', 'Gyatt', 'Slang'],
  Rizz: ['Gyatt', 'Aura', 'Fanum tax', 'Slang'],
  Gyatt: ['Rizz', 'Fanum tax', 'Slang'],
  Aura: ['Sigma', 'Rizz', 'Mogging', 'Slang'],
  Mogging: ['Mewing', 'Sigma', 'Aura', 'Slang'],
  Mewing: ['Mogging', 'Slang'],
  Cap: ['No cap', 'Slang'],
  'No cap': ['Cap', 'Slang'],
  Delulu: ['Slang', 'Rizz'],
  Slang: [
    'Cap',
    'No cap',
    'Delulu',
    'Rizz',
    'Gyatt',
    'Sigma',
    'Fanum tax',
    'Aura',
    'Mogging',
    'Mewing',
    'Chuzz',
    'Huzz',
    'Fuzz',
    'Brainrot',
    'Skibidi toilet',
  ],
  'What the Sigma?': ['Sigma', 'Brainrot', 'Skibidi toilet', 'Slang'],
};
