/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginCallbackRouteImport } from './routes/login/callback'
import { Route as LearnerSettingsRouteImport } from './routes/learner/settings'
import { Route as LearnerMyCoursesRouteImport } from './routes/learner/my-courses'
import { Route as LearnerDashboardRouteImport } from './routes/learner/dashboard'
import { Route as LearnerChallengesRouteImport } from './routes/learner/challenges'
import { Route as EditorCourseIdRouteImport } from './routes/editor/$courseId'
import { Route as ContributorTeamsRouteImport } from './routes/contributor/teams'
import { Route as ContributorSettingsRouteImport } from './routes/contributor/settings'
import { Route as ContributorDashboardRouteImport } from './routes/contributor/dashboard'
import { Route as AdminUserManagementRouteImport } from './routes/admin/user-management'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCourseModerationRouteImport } from './routes/admin/course-moderation'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedTeamsIndexRouteImport } from './routes/_authenticated/teams/index'
import { Route as AuthenticatedCoursesIndexRouteImport } from './routes/_authenticated/courses/index'
import { Route as ContributorTeamIdCoursesRouteImport } from './routes/contributor/$teamId/courses'
import { Route as AuthenticatedTeamsCreateRouteImport } from './routes/_authenticated/teams/create'
import { Route as AuthenticatedTeamsTeamIdRouteImport } from './routes/_authenticated/teams/$teamId'
import { Route as AuthenticatedCoursesCreateRouteImport } from './routes/_authenticated/courses/create'
import { Route as AuthenticatedCoursesCourseIdRouteImport } from './routes/_authenticated/courses/$courseId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerSettingsRoute = LearnerSettingsRouteImport.update({
  id: '/learner/settings',
  path: '/learner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerMyCoursesRoute = LearnerMyCoursesRouteImport.update({
  id: '/learner/my-courses',
  path: '/learner/my-courses',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: '/learner/dashboard',
  path: '/learner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerChallengesRoute = LearnerChallengesRouteImport.update({
  id: '/learner/challenges',
  path: '/learner/challenges',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorCourseIdRoute = EditorCourseIdRouteImport.update({
  id: '/editor/$courseId',
  path: '/editor/$courseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorTeamsRoute = ContributorTeamsRouteImport.update({
  id: '/contributor/teams',
  path: '/contributor/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorSettingsRoute = ContributorSettingsRouteImport.update({
  id: '/contributor/settings',
  path: '/contributor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorDashboardRoute = ContributorDashboardRouteImport.update({
  id: '/contributor/dashboard',
  path: '/contributor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserManagementRoute = AdminUserManagementRouteImport.update({
  id: '/admin/user-management',
  path: '/admin/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourseModerationRoute = AdminCourseModerationRouteImport.update({
  id: '/admin/course-moderation',
  path: '/admin/course-moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedTeamsIndexRoute = AuthenticatedTeamsIndexRouteImport.update({
  id: '/teams/',
  path: '/teams/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCoursesIndexRoute =
  AuthenticatedCoursesIndexRouteImport.update({
    id: '/courses/',
    path: '/courses/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ContributorTeamIdCoursesRoute =
  ContributorTeamIdCoursesRouteImport.update({
    id: '/contributor/$teamId/courses',
    path: '/contributor/$teamId/courses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedTeamsCreateRoute =
  AuthenticatedTeamsCreateRouteImport.update({
    id: '/teams/create',
    path: '/teams/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedTeamsTeamIdRoute =
  AuthenticatedTeamsTeamIdRouteImport.update({
    id: '/teams/$teamId',
    path: '/teams/$teamId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesCreateRoute =
  AuthenticatedCoursesCreateRouteImport.update({
    id: '/courses/create',
    path: '/courses/create',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCoursesCourseIdRoute =
  AuthenticatedCoursesCourseIdRouteImport.update({
    id: '/courses/$courseId',
    path: '/courses/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/course-moderation': typeof AdminCourseModerationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/contributor/dashboard': typeof ContributorDashboardRoute
  '/contributor/settings': typeof ContributorSettingsRoute
  '/contributor/teams': typeof ContributorTeamsRoute
  '/editor/$courseId': typeof EditorCourseIdRoute
  '/learner/challenges': typeof LearnerChallengesRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/my-courses': typeof LearnerMyCoursesRoute
  '/learner/settings': typeof LearnerSettingsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/courses/create': typeof AuthenticatedCoursesCreateRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/contributor/$teamId/courses': typeof ContributorTeamIdCoursesRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/course-moderation': typeof AdminCourseModerationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/contributor/dashboard': typeof ContributorDashboardRoute
  '/contributor/settings': typeof ContributorSettingsRoute
  '/contributor/teams': typeof ContributorTeamsRoute
  '/editor/$courseId': typeof EditorCourseIdRoute
  '/learner/challenges': typeof LearnerChallengesRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/my-courses': typeof LearnerMyCoursesRoute
  '/learner/settings': typeof LearnerSettingsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
  '/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/courses/create': typeof AuthenticatedCoursesCreateRoute
  '/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/contributor/$teamId/courses': typeof ContributorTeamIdCoursesRoute
  '/courses': typeof AuthenticatedCoursesIndexRoute
  '/teams': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/course-moderation': typeof AdminCourseModerationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/contributor/dashboard': typeof ContributorDashboardRoute
  '/contributor/settings': typeof ContributorSettingsRoute
  '/contributor/teams': typeof ContributorTeamsRoute
  '/editor/$courseId': typeof EditorCourseIdRoute
  '/learner/challenges': typeof LearnerChallengesRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/my-courses': typeof LearnerMyCoursesRoute
  '/learner/settings': typeof LearnerSettingsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/courses/$courseId': typeof AuthenticatedCoursesCourseIdRoute
  '/_authenticated/courses/create': typeof AuthenticatedCoursesCreateRoute
  '/_authenticated/teams/$teamId': typeof AuthenticatedTeamsTeamIdRoute
  '/_authenticated/teams/create': typeof AuthenticatedTeamsCreateRoute
  '/contributor/$teamId/courses': typeof ContributorTeamIdCoursesRoute
  '/_authenticated/courses/': typeof AuthenticatedCoursesIndexRoute
  '/_authenticated/teams/': typeof AuthenticatedTeamsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/profile'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/editor/$courseId'
    | '/learner/challenges'
    | '/learner/dashboard'
    | '/learner/my-courses'
    | '/learner/settings'
    | '/login/callback'
    | '/login'
    | '/courses/$courseId'
    | '/courses/create'
    | '/teams/$teamId'
    | '/teams/create'
    | '/contributor/$teamId/courses'
    | '/courses'
    | '/teams'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/profile'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/editor/$courseId'
    | '/learner/challenges'
    | '/learner/dashboard'
    | '/learner/my-courses'
    | '/learner/settings'
    | '/login/callback'
    | '/login'
    | '/courses/$courseId'
    | '/courses/create'
    | '/teams/$teamId'
    | '/teams/create'
    | '/contributor/$teamId/courses'
    | '/courses'
    | '/teams'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/profile'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/editor/$courseId'
    | '/learner/challenges'
    | '/learner/dashboard'
    | '/learner/my-courses'
    | '/learner/settings'
    | '/login/callback'
    | '/login/'
    | '/_authenticated/courses/$courseId'
    | '/_authenticated/courses/create'
    | '/_authenticated/teams/$teamId'
    | '/_authenticated/teams/create'
    | '/contributor/$teamId/courses'
    | '/_authenticated/courses/'
    | '/_authenticated/teams/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  AdminCourseModerationRoute: typeof AdminCourseModerationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
  ContributorDashboardRoute: typeof ContributorDashboardRoute
  ContributorSettingsRoute: typeof ContributorSettingsRoute
  ContributorTeamsRoute: typeof ContributorTeamsRoute
  EditorCourseIdRoute: typeof EditorCourseIdRoute
  LearnerChallengesRoute: typeof LearnerChallengesRoute
  LearnerDashboardRoute: typeof LearnerDashboardRoute
  LearnerMyCoursesRoute: typeof LearnerMyCoursesRoute
  LearnerSettingsRoute: typeof LearnerSettingsRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ContributorTeamIdCoursesRoute: typeof ContributorTeamIdCoursesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/settings': {
      id: '/learner/settings'
      path: '/learner/settings'
      fullPath: '/learner/settings'
      preLoaderRoute: typeof LearnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/my-courses': {
      id: '/learner/my-courses'
      path: '/learner/my-courses'
      fullPath: '/learner/my-courses'
      preLoaderRoute: typeof LearnerMyCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/dashboard': {
      id: '/learner/dashboard'
      path: '/learner/dashboard'
      fullPath: '/learner/dashboard'
      preLoaderRoute: typeof LearnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/challenges': {
      id: '/learner/challenges'
      path: '/learner/challenges'
      fullPath: '/learner/challenges'
      preLoaderRoute: typeof LearnerChallengesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/$courseId': {
      id: '/editor/$courseId'
      path: '/editor/$courseId'
      fullPath: '/editor/$courseId'
      preLoaderRoute: typeof EditorCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/teams': {
      id: '/contributor/teams'
      path: '/contributor/teams'
      fullPath: '/contributor/teams'
      preLoaderRoute: typeof ContributorTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/settings': {
      id: '/contributor/settings'
      path: '/contributor/settings'
      fullPath: '/contributor/settings'
      preLoaderRoute: typeof ContributorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/dashboard': {
      id: '/contributor/dashboard'
      path: '/contributor/dashboard'
      fullPath: '/contributor/dashboard'
      preLoaderRoute: typeof ContributorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course-moderation': {
      id: '/admin/course-moderation'
      path: '/admin/course-moderation'
      fullPath: '/admin/course-moderation'
      preLoaderRoute: typeof AdminCourseModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/': {
      id: '/_authenticated/teams/'
      path: '/teams'
      fullPath: '/teams'
      preLoaderRoute: typeof AuthenticatedTeamsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/': {
      id: '/_authenticated/courses/'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof AuthenticatedCoursesIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/contributor/$teamId/courses': {
      id: '/contributor/$teamId/courses'
      path: '/contributor/$teamId/courses'
      fullPath: '/contributor/$teamId/courses'
      preLoaderRoute: typeof ContributorTeamIdCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/teams/create': {
      id: '/_authenticated/teams/create'
      path: '/teams/create'
      fullPath: '/teams/create'
      preLoaderRoute: typeof AuthenticatedTeamsCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/teams/$teamId': {
      id: '/_authenticated/teams/$teamId'
      path: '/teams/$teamId'
      fullPath: '/teams/$teamId'
      preLoaderRoute: typeof AuthenticatedTeamsTeamIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/create': {
      id: '/_authenticated/courses/create'
      path: '/courses/create'
      fullPath: '/courses/create'
      preLoaderRoute: typeof AuthenticatedCoursesCreateRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/courses/$courseId': {
      id: '/_authenticated/courses/$courseId'
      path: '/courses/$courseId'
      fullPath: '/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedCoursesCourseIdRoute: typeof AuthenticatedCoursesCourseIdRoute
  AuthenticatedCoursesCreateRoute: typeof AuthenticatedCoursesCreateRoute
  AuthenticatedTeamsTeamIdRoute: typeof AuthenticatedTeamsTeamIdRoute
  AuthenticatedTeamsCreateRoute: typeof AuthenticatedTeamsCreateRoute
  AuthenticatedCoursesIndexRoute: typeof AuthenticatedCoursesIndexRoute
  AuthenticatedTeamsIndexRoute: typeof AuthenticatedTeamsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedCoursesCourseIdRoute: AuthenticatedCoursesCourseIdRoute,
  AuthenticatedCoursesCreateRoute: AuthenticatedCoursesCreateRoute,
  AuthenticatedTeamsTeamIdRoute: AuthenticatedTeamsTeamIdRoute,
  AuthenticatedTeamsCreateRoute: AuthenticatedTeamsCreateRoute,
  AuthenticatedCoursesIndexRoute: AuthenticatedCoursesIndexRoute,
  AuthenticatedTeamsIndexRoute: AuthenticatedTeamsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RegisterRoute: RegisterRoute,
  AdminCourseModerationRoute: AdminCourseModerationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
  ContributorDashboardRoute: ContributorDashboardRoute,
  ContributorSettingsRoute: ContributorSettingsRoute,
  ContributorTeamsRoute: ContributorTeamsRoute,
  EditorCourseIdRoute: EditorCourseIdRoute,
  LearnerChallengesRoute: LearnerChallengesRoute,
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearnerMyCoursesRoute: LearnerMyCoursesRoute,
  LearnerSettingsRoute: LearnerSettingsRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
  ContributorTeamIdCoursesRoute: ContributorTeamIdCoursesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
