/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginCallbackRouteImport } from './routes/login/callback'
import { Route as LearnerSettingsRouteImport } from './routes/learner/settings'
import { Route as LearnerDashboardRouteImport } from './routes/learner/dashboard'
import { Route as ContributorTeamsRouteImport } from './routes/contributor/teams'
import { Route as ContributorSettingsRouteImport } from './routes/contributor/settings'
import { Route as ContributorDashboardRouteImport } from './routes/contributor/dashboard'
import { Route as AdminUserManagementRouteImport } from './routes/admin/user-management'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminCourseModerationRouteImport } from './routes/admin/course-moderation'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerSettingsRoute = LearnerSettingsRouteImport.update({
  id: '/learner/settings',
  path: '/learner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnerDashboardRoute = LearnerDashboardRouteImport.update({
  id: '/learner/dashboard',
  path: '/learner/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorTeamsRoute = ContributorTeamsRouteImport.update({
  id: '/contributor/teams',
  path: '/contributor/teams',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorSettingsRoute = ContributorSettingsRouteImport.update({
  id: '/contributor/settings',
  path: '/contributor/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ContributorDashboardRoute = ContributorDashboardRouteImport.update({
  id: '/contributor/dashboard',
  path: '/contributor/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUserManagementRoute = AdminUserManagementRouteImport.update({
  id: '/admin/user-management',
  path: '/admin/user-management',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCourseModerationRoute = AdminCourseModerationRouteImport.update({
  id: '/admin/course-moderation',
  path: '/admin/course-moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/course-moderation': typeof AdminCourseModerationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/contributor/dashboard': typeof ContributorDashboardRoute
  '/contributor/settings': typeof ContributorSettingsRoute
  '/contributor/teams': typeof ContributorTeamsRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/settings': typeof LearnerSettingsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/admin/course-moderation': typeof AdminCourseModerationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/contributor/dashboard': typeof ContributorDashboardRoute
  '/contributor/settings': typeof ContributorSettingsRoute
  '/contributor/teams': typeof ContributorTeamsRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/settings': typeof LearnerSettingsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/admin/course-moderation': typeof AdminCourseModerationRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/user-management': typeof AdminUserManagementRoute
  '/contributor/dashboard': typeof ContributorDashboardRoute
  '/contributor/settings': typeof ContributorSettingsRoute
  '/contributor/teams': typeof ContributorTeamsRoute
  '/learner/dashboard': typeof LearnerDashboardRoute
  '/learner/settings': typeof LearnerSettingsRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login/': typeof LoginIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/register'
    | '/profile'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/learner/dashboard'
    | '/learner/settings'
    | '/login/callback'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/register'
    | '/profile'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/learner/dashboard'
    | '/learner/settings'
    | '/login/callback'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/register'
    | '/_authenticated/profile'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/learner/dashboard'
    | '/learner/settings'
    | '/login/callback'
    | '/login/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  RegisterRoute: typeof RegisterRoute
  AdminCourseModerationRoute: typeof AdminCourseModerationRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUserManagementRoute: typeof AdminUserManagementRoute
  ContributorDashboardRoute: typeof ContributorDashboardRoute
  ContributorSettingsRoute: typeof ContributorSettingsRoute
  ContributorTeamsRoute: typeof ContributorTeamsRoute
  LearnerDashboardRoute: typeof LearnerDashboardRoute
  LearnerSettingsRoute: typeof LearnerSettingsRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/settings': {
      id: '/learner/settings'
      path: '/learner/settings'
      fullPath: '/learner/settings'
      preLoaderRoute: typeof LearnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learner/dashboard': {
      id: '/learner/dashboard'
      path: '/learner/dashboard'
      fullPath: '/learner/dashboard'
      preLoaderRoute: typeof LearnerDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/teams': {
      id: '/contributor/teams'
      path: '/contributor/teams'
      fullPath: '/contributor/teams'
      preLoaderRoute: typeof ContributorTeamsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/settings': {
      id: '/contributor/settings'
      path: '/contributor/settings'
      fullPath: '/contributor/settings'
      preLoaderRoute: typeof ContributorSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/dashboard': {
      id: '/contributor/dashboard'
      path: '/contributor/dashboard'
      fullPath: '/contributor/dashboard'
      preLoaderRoute: typeof ContributorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/user-management': {
      id: '/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AdminUserManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/course-moderation': {
      id: '/admin/course-moderation'
      path: '/admin/course-moderation'
      fullPath: '/admin/course-moderation'
      preLoaderRoute: typeof AdminCourseModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  RegisterRoute: RegisterRoute,
  AdminCourseModerationRoute: AdminCourseModerationRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUserManagementRoute: AdminUserManagementRoute,
  ContributorDashboardRoute: ContributorDashboardRoute,
  ContributorSettingsRoute: ContributorSettingsRoute,
  ContributorTeamsRoute: ContributorTeamsRoute,
  LearnerDashboardRoute: LearnerDashboardRoute,
  LearnerSettingsRoute: LearnerSettingsRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
