/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as PreferenceRouteImport } from './routes/preference'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginIndexRouteImport } from './routes/login/index'
import { Route as LoginCallbackRouteImport } from './routes/login/callback'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as ContributorEditorCourseIdRouteImport } from './routes/contributor/editor/$courseId'
import { Route as ContributorTeamIdCoursesRouteImport } from './routes/contributor/$teamId/courses'
import { Route as AuthenticatedLearnerSettingsRouteImport } from './routes/_authenticated/learner/settings'
import { Route as AuthenticatedLearnerMyCoursesRouteImport } from './routes/_authenticated/learner/my-courses'
import { Route as AuthenticatedLearnerGlossaryRouteImport } from './routes/_authenticated/learner/glossary'
import { Route as AuthenticatedLearnerFaqRouteImport } from './routes/_authenticated/learner/faq'
import { Route as AuthenticatedLearnerDiscoverRouteImport } from './routes/_authenticated/learner/discover'
import { Route as AuthenticatedLearnerDashboardRouteImport } from './routes/_authenticated/learner/dashboard'
import { Route as AuthenticatedContributorTeamsRouteImport } from './routes/_authenticated/contributor/teams'
import { Route as AuthenticatedContributorSettingsRouteImport } from './routes/_authenticated/contributor/settings'
import { Route as AuthenticatedContributorGlossaryRouteImport } from './routes/_authenticated/contributor/glossary'
import { Route as AuthenticatedContributorFaqRouteImport } from './routes/_authenticated/contributor/faq'
import { Route as AuthenticatedContributorDiscoverRouteImport } from './routes/_authenticated/contributor/discover'
import { Route as AuthenticatedContributorDashboardRouteImport } from './routes/_authenticated/contributor/dashboard'
import { Route as AuthenticatedAdminUserManagementRouteImport } from './routes/_authenticated/admin/user-management'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin/settings'
import { Route as AuthenticatedAdminGraphRouteImport } from './routes/_authenticated/admin/graph'
import { Route as AuthenticatedAdminGlossaryRouteImport } from './routes/_authenticated/admin/glossary'
import { Route as AuthenticatedAdminFaqRouteImport } from './routes/_authenticated/admin/faq'
import { Route as AuthenticatedAdminDiscoverRouteImport } from './routes/_authenticated/admin/discover'
import { Route as AuthenticatedAdminDashboardRouteImport } from './routes/_authenticated/admin/dashboard'
import { Route as AuthenticatedAdminCourseModerationRouteImport } from './routes/_authenticated/admin/course-moderation'
import { Route as AuthenticatedLearnerCoursesCourseIdRouteImport } from './routes/_authenticated/learner/courses/$courseId'
import { Route as AuthenticatedAdminReviewVersionIdRouteImport } from './routes/_authenticated/admin/review/$versionId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const PreferenceRoute = PreferenceRouteImport.update({
  id: '/preference',
  path: '/preference',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginIndexRoute = LoginIndexRouteImport.update({
  id: '/login/',
  path: '/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginCallbackRoute = LoginCallbackRouteImport.update({
  id: '/login/callback',
  path: '/login/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ContributorEditorCourseIdRoute =
  ContributorEditorCourseIdRouteImport.update({
    id: '/contributor/editor/$courseId',
    path: '/contributor/editor/$courseId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContributorTeamIdCoursesRoute =
  ContributorTeamIdCoursesRouteImport.update({
    id: '/contributor/$teamId/courses',
    path: '/contributor/$teamId/courses',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedLearnerSettingsRoute =
  AuthenticatedLearnerSettingsRouteImport.update({
    id: '/learner/settings',
    path: '/learner/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnerMyCoursesRoute =
  AuthenticatedLearnerMyCoursesRouteImport.update({
    id: '/learner/my-courses',
    path: '/learner/my-courses',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnerGlossaryRoute =
  AuthenticatedLearnerGlossaryRouteImport.update({
    id: '/learner/glossary',
    path: '/learner/glossary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnerFaqRoute = AuthenticatedLearnerFaqRouteImport.update({
  id: '/learner/faq',
  path: '/learner/faq',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedLearnerDiscoverRoute =
  AuthenticatedLearnerDiscoverRouteImport.update({
    id: '/learner/discover',
    path: '/learner/discover',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnerDashboardRoute =
  AuthenticatedLearnerDashboardRouteImport.update({
    id: '/learner/dashboard',
    path: '/learner/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContributorTeamsRoute =
  AuthenticatedContributorTeamsRouteImport.update({
    id: '/contributor/teams',
    path: '/contributor/teams',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContributorSettingsRoute =
  AuthenticatedContributorSettingsRouteImport.update({
    id: '/contributor/settings',
    path: '/contributor/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContributorGlossaryRoute =
  AuthenticatedContributorGlossaryRouteImport.update({
    id: '/contributor/glossary',
    path: '/contributor/glossary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContributorFaqRoute =
  AuthenticatedContributorFaqRouteImport.update({
    id: '/contributor/faq',
    path: '/contributor/faq',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContributorDiscoverRoute =
  AuthenticatedContributorDiscoverRouteImport.update({
    id: '/contributor/discover',
    path: '/contributor/discover',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedContributorDashboardRoute =
  AuthenticatedContributorDashboardRouteImport.update({
    id: '/contributor/dashboard',
    path: '/contributor/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUserManagementRoute =
  AuthenticatedAdminUserManagementRouteImport.update({
    id: '/admin/user-management',
    path: '/admin/user-management',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/admin/settings',
    path: '/admin/settings',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminGraphRoute = AuthenticatedAdminGraphRouteImport.update({
  id: '/admin/graph',
  path: '/admin/graph',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminGlossaryRoute =
  AuthenticatedAdminGlossaryRouteImport.update({
    id: '/admin/glossary',
    path: '/admin/glossary',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminFaqRoute = AuthenticatedAdminFaqRouteImport.update({
  id: '/admin/faq',
  path: '/admin/faq',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminDiscoverRoute =
  AuthenticatedAdminDiscoverRouteImport.update({
    id: '/admin/discover',
    path: '/admin/discover',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminDashboardRoute =
  AuthenticatedAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCourseModerationRoute =
  AuthenticatedAdminCourseModerationRouteImport.update({
    id: '/admin/course-moderation',
    path: '/admin/course-moderation',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLearnerCoursesCourseIdRoute =
  AuthenticatedLearnerCoursesCourseIdRouteImport.update({
    id: '/learner/courses/$courseId',
    path: '/learner/courses/$courseId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminReviewVersionIdRoute =
  AuthenticatedAdminReviewVersionIdRouteImport.update({
    id: '/admin/review/$versionId',
    path: '/admin/review/$versionId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/preference': typeof PreferenceRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
  '/admin/course-moderation': typeof AuthenticatedAdminCourseModerationRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/discover': typeof AuthenticatedAdminDiscoverRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/glossary': typeof AuthenticatedAdminGlossaryRoute
  '/admin/graph': typeof AuthenticatedAdminGraphRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/contributor/dashboard': typeof AuthenticatedContributorDashboardRoute
  '/contributor/discover': typeof AuthenticatedContributorDiscoverRoute
  '/contributor/faq': typeof AuthenticatedContributorFaqRoute
  '/contributor/glossary': typeof AuthenticatedContributorGlossaryRoute
  '/contributor/settings': typeof AuthenticatedContributorSettingsRoute
  '/contributor/teams': typeof AuthenticatedContributorTeamsRoute
  '/learner/dashboard': typeof AuthenticatedLearnerDashboardRoute
  '/learner/discover': typeof AuthenticatedLearnerDiscoverRoute
  '/learner/faq': typeof AuthenticatedLearnerFaqRoute
  '/learner/glossary': typeof AuthenticatedLearnerGlossaryRoute
  '/learner/my-courses': typeof AuthenticatedLearnerMyCoursesRoute
  '/learner/settings': typeof AuthenticatedLearnerSettingsRoute
  '/contributor/$teamId/courses': typeof ContributorTeamIdCoursesRoute
  '/contributor/editor/$courseId': typeof ContributorEditorCourseIdRoute
  '/admin/review/$versionId': typeof AuthenticatedAdminReviewVersionIdRoute
  '/learner/courses/$courseId': typeof AuthenticatedLearnerCoursesCourseIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preference': typeof PreferenceRoute
  '/register': typeof RegisterRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login': typeof LoginIndexRoute
  '/admin/course-moderation': typeof AuthenticatedAdminCourseModerationRoute
  '/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/admin/discover': typeof AuthenticatedAdminDiscoverRoute
  '/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/admin/glossary': typeof AuthenticatedAdminGlossaryRoute
  '/admin/graph': typeof AuthenticatedAdminGraphRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/contributor/dashboard': typeof AuthenticatedContributorDashboardRoute
  '/contributor/discover': typeof AuthenticatedContributorDiscoverRoute
  '/contributor/faq': typeof AuthenticatedContributorFaqRoute
  '/contributor/glossary': typeof AuthenticatedContributorGlossaryRoute
  '/contributor/settings': typeof AuthenticatedContributorSettingsRoute
  '/contributor/teams': typeof AuthenticatedContributorTeamsRoute
  '/learner/dashboard': typeof AuthenticatedLearnerDashboardRoute
  '/learner/discover': typeof AuthenticatedLearnerDiscoverRoute
  '/learner/faq': typeof AuthenticatedLearnerFaqRoute
  '/learner/glossary': typeof AuthenticatedLearnerGlossaryRoute
  '/learner/my-courses': typeof AuthenticatedLearnerMyCoursesRoute
  '/learner/settings': typeof AuthenticatedLearnerSettingsRoute
  '/contributor/$teamId/courses': typeof ContributorTeamIdCoursesRoute
  '/contributor/editor/$courseId': typeof ContributorEditorCourseIdRoute
  '/admin/review/$versionId': typeof AuthenticatedAdminReviewVersionIdRoute
  '/learner/courses/$courseId': typeof AuthenticatedLearnerCoursesCourseIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/preference': typeof PreferenceRoute
  '/register': typeof RegisterRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/login/callback': typeof LoginCallbackRoute
  '/login/': typeof LoginIndexRoute
  '/_authenticated/admin/course-moderation': typeof AuthenticatedAdminCourseModerationRoute
  '/_authenticated/admin/dashboard': typeof AuthenticatedAdminDashboardRoute
  '/_authenticated/admin/discover': typeof AuthenticatedAdminDiscoverRoute
  '/_authenticated/admin/faq': typeof AuthenticatedAdminFaqRoute
  '/_authenticated/admin/glossary': typeof AuthenticatedAdminGlossaryRoute
  '/_authenticated/admin/graph': typeof AuthenticatedAdminGraphRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/user-management': typeof AuthenticatedAdminUserManagementRoute
  '/_authenticated/contributor/dashboard': typeof AuthenticatedContributorDashboardRoute
  '/_authenticated/contributor/discover': typeof AuthenticatedContributorDiscoverRoute
  '/_authenticated/contributor/faq': typeof AuthenticatedContributorFaqRoute
  '/_authenticated/contributor/glossary': typeof AuthenticatedContributorGlossaryRoute
  '/_authenticated/contributor/settings': typeof AuthenticatedContributorSettingsRoute
  '/_authenticated/contributor/teams': typeof AuthenticatedContributorTeamsRoute
  '/_authenticated/learner/dashboard': typeof AuthenticatedLearnerDashboardRoute
  '/_authenticated/learner/discover': typeof AuthenticatedLearnerDiscoverRoute
  '/_authenticated/learner/faq': typeof AuthenticatedLearnerFaqRoute
  '/_authenticated/learner/glossary': typeof AuthenticatedLearnerGlossaryRoute
  '/_authenticated/learner/my-courses': typeof AuthenticatedLearnerMyCoursesRoute
  '/_authenticated/learner/settings': typeof AuthenticatedLearnerSettingsRoute
  '/contributor/$teamId/courses': typeof ContributorTeamIdCoursesRoute
  '/contributor/editor/$courseId': typeof ContributorEditorCourseIdRoute
  '/_authenticated/admin/review/$versionId': typeof AuthenticatedAdminReviewVersionIdRoute
  '/_authenticated/learner/courses/$courseId': typeof AuthenticatedLearnerCoursesCourseIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/preference'
    | '/register'
    | '/profile'
    | '/login/callback'
    | '/login'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/discover'
    | '/admin/faq'
    | '/admin/glossary'
    | '/admin/graph'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/discover'
    | '/contributor/faq'
    | '/contributor/glossary'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/learner/dashboard'
    | '/learner/discover'
    | '/learner/faq'
    | '/learner/glossary'
    | '/learner/my-courses'
    | '/learner/settings'
    | '/contributor/$teamId/courses'
    | '/contributor/editor/$courseId'
    | '/admin/review/$versionId'
    | '/learner/courses/$courseId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preference'
    | '/register'
    | '/profile'
    | '/login/callback'
    | '/login'
    | '/admin/course-moderation'
    | '/admin/dashboard'
    | '/admin/discover'
    | '/admin/faq'
    | '/admin/glossary'
    | '/admin/graph'
    | '/admin/settings'
    | '/admin/user-management'
    | '/contributor/dashboard'
    | '/contributor/discover'
    | '/contributor/faq'
    | '/contributor/glossary'
    | '/contributor/settings'
    | '/contributor/teams'
    | '/learner/dashboard'
    | '/learner/discover'
    | '/learner/faq'
    | '/learner/glossary'
    | '/learner/my-courses'
    | '/learner/settings'
    | '/contributor/$teamId/courses'
    | '/contributor/editor/$courseId'
    | '/admin/review/$versionId'
    | '/learner/courses/$courseId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/preference'
    | '/register'
    | '/_authenticated/profile'
    | '/login/callback'
    | '/login/'
    | '/_authenticated/admin/course-moderation'
    | '/_authenticated/admin/dashboard'
    | '/_authenticated/admin/discover'
    | '/_authenticated/admin/faq'
    | '/_authenticated/admin/glossary'
    | '/_authenticated/admin/graph'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/user-management'
    | '/_authenticated/contributor/dashboard'
    | '/_authenticated/contributor/discover'
    | '/_authenticated/contributor/faq'
    | '/_authenticated/contributor/glossary'
    | '/_authenticated/contributor/settings'
    | '/_authenticated/contributor/teams'
    | '/_authenticated/learner/dashboard'
    | '/_authenticated/learner/discover'
    | '/_authenticated/learner/faq'
    | '/_authenticated/learner/glossary'
    | '/_authenticated/learner/my-courses'
    | '/_authenticated/learner/settings'
    | '/contributor/$teamId/courses'
    | '/contributor/editor/$courseId'
    | '/_authenticated/admin/review/$versionId'
    | '/_authenticated/learner/courses/$courseId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PreferenceRoute: typeof PreferenceRoute
  RegisterRoute: typeof RegisterRoute
  LoginCallbackRoute: typeof LoginCallbackRoute
  LoginIndexRoute: typeof LoginIndexRoute
  ContributorTeamIdCoursesRoute: typeof ContributorTeamIdCoursesRoute
  ContributorEditorCourseIdRoute: typeof ContributorEditorCourseIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preference': {
      id: '/preference'
      path: '/preference'
      fullPath: '/preference'
      preLoaderRoute: typeof PreferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/': {
      id: '/login/'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login/callback': {
      id: '/login/callback'
      path: '/login/callback'
      fullPath: '/login/callback'
      preLoaderRoute: typeof LoginCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/contributor/editor/$courseId': {
      id: '/contributor/editor/$courseId'
      path: '/contributor/editor/$courseId'
      fullPath: '/contributor/editor/$courseId'
      preLoaderRoute: typeof ContributorEditorCourseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contributor/$teamId/courses': {
      id: '/contributor/$teamId/courses'
      path: '/contributor/$teamId/courses'
      fullPath: '/contributor/$teamId/courses'
      preLoaderRoute: typeof ContributorTeamIdCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/learner/settings': {
      id: '/_authenticated/learner/settings'
      path: '/learner/settings'
      fullPath: '/learner/settings'
      preLoaderRoute: typeof AuthenticatedLearnerSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learner/my-courses': {
      id: '/_authenticated/learner/my-courses'
      path: '/learner/my-courses'
      fullPath: '/learner/my-courses'
      preLoaderRoute: typeof AuthenticatedLearnerMyCoursesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learner/glossary': {
      id: '/_authenticated/learner/glossary'
      path: '/learner/glossary'
      fullPath: '/learner/glossary'
      preLoaderRoute: typeof AuthenticatedLearnerGlossaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learner/faq': {
      id: '/_authenticated/learner/faq'
      path: '/learner/faq'
      fullPath: '/learner/faq'
      preLoaderRoute: typeof AuthenticatedLearnerFaqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learner/discover': {
      id: '/_authenticated/learner/discover'
      path: '/learner/discover'
      fullPath: '/learner/discover'
      preLoaderRoute: typeof AuthenticatedLearnerDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learner/dashboard': {
      id: '/_authenticated/learner/dashboard'
      path: '/learner/dashboard'
      fullPath: '/learner/dashboard'
      preLoaderRoute: typeof AuthenticatedLearnerDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributor/teams': {
      id: '/_authenticated/contributor/teams'
      path: '/contributor/teams'
      fullPath: '/contributor/teams'
      preLoaderRoute: typeof AuthenticatedContributorTeamsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributor/settings': {
      id: '/_authenticated/contributor/settings'
      path: '/contributor/settings'
      fullPath: '/contributor/settings'
      preLoaderRoute: typeof AuthenticatedContributorSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributor/glossary': {
      id: '/_authenticated/contributor/glossary'
      path: '/contributor/glossary'
      fullPath: '/contributor/glossary'
      preLoaderRoute: typeof AuthenticatedContributorGlossaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributor/faq': {
      id: '/_authenticated/contributor/faq'
      path: '/contributor/faq'
      fullPath: '/contributor/faq'
      preLoaderRoute: typeof AuthenticatedContributorFaqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributor/discover': {
      id: '/_authenticated/contributor/discover'
      path: '/contributor/discover'
      fullPath: '/contributor/discover'
      preLoaderRoute: typeof AuthenticatedContributorDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/contributor/dashboard': {
      id: '/_authenticated/contributor/dashboard'
      path: '/contributor/dashboard'
      fullPath: '/contributor/dashboard'
      preLoaderRoute: typeof AuthenticatedContributorDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/user-management': {
      id: '/_authenticated/admin/user-management'
      path: '/admin/user-management'
      fullPath: '/admin/user-management'
      preLoaderRoute: typeof AuthenticatedAdminUserManagementRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/graph': {
      id: '/_authenticated/admin/graph'
      path: '/admin/graph'
      fullPath: '/admin/graph'
      preLoaderRoute: typeof AuthenticatedAdminGraphRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/glossary': {
      id: '/_authenticated/admin/glossary'
      path: '/admin/glossary'
      fullPath: '/admin/glossary'
      preLoaderRoute: typeof AuthenticatedAdminGlossaryRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/faq': {
      id: '/_authenticated/admin/faq'
      path: '/admin/faq'
      fullPath: '/admin/faq'
      preLoaderRoute: typeof AuthenticatedAdminFaqRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/discover': {
      id: '/_authenticated/admin/discover'
      path: '/admin/discover'
      fullPath: '/admin/discover'
      preLoaderRoute: typeof AuthenticatedAdminDiscoverRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/dashboard': {
      id: '/_authenticated/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/course-moderation': {
      id: '/_authenticated/admin/course-moderation'
      path: '/admin/course-moderation'
      fullPath: '/admin/course-moderation'
      preLoaderRoute: typeof AuthenticatedAdminCourseModerationRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/learner/courses/$courseId': {
      id: '/_authenticated/learner/courses/$courseId'
      path: '/learner/courses/$courseId'
      fullPath: '/learner/courses/$courseId'
      preLoaderRoute: typeof AuthenticatedLearnerCoursesCourseIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/review/$versionId': {
      id: '/_authenticated/admin/review/$versionId'
      path: '/admin/review/$versionId'
      fullPath: '/admin/review/$versionId'
      preLoaderRoute: typeof AuthenticatedAdminReviewVersionIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedAdminCourseModerationRoute: typeof AuthenticatedAdminCourseModerationRoute
  AuthenticatedAdminDashboardRoute: typeof AuthenticatedAdminDashboardRoute
  AuthenticatedAdminDiscoverRoute: typeof AuthenticatedAdminDiscoverRoute
  AuthenticatedAdminFaqRoute: typeof AuthenticatedAdminFaqRoute
  AuthenticatedAdminGlossaryRoute: typeof AuthenticatedAdminGlossaryRoute
  AuthenticatedAdminGraphRoute: typeof AuthenticatedAdminGraphRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminUserManagementRoute: typeof AuthenticatedAdminUserManagementRoute
  AuthenticatedContributorDashboardRoute: typeof AuthenticatedContributorDashboardRoute
  AuthenticatedContributorDiscoverRoute: typeof AuthenticatedContributorDiscoverRoute
  AuthenticatedContributorFaqRoute: typeof AuthenticatedContributorFaqRoute
  AuthenticatedContributorGlossaryRoute: typeof AuthenticatedContributorGlossaryRoute
  AuthenticatedContributorSettingsRoute: typeof AuthenticatedContributorSettingsRoute
  AuthenticatedContributorTeamsRoute: typeof AuthenticatedContributorTeamsRoute
  AuthenticatedLearnerDashboardRoute: typeof AuthenticatedLearnerDashboardRoute
  AuthenticatedLearnerDiscoverRoute: typeof AuthenticatedLearnerDiscoverRoute
  AuthenticatedLearnerFaqRoute: typeof AuthenticatedLearnerFaqRoute
  AuthenticatedLearnerGlossaryRoute: typeof AuthenticatedLearnerGlossaryRoute
  AuthenticatedLearnerMyCoursesRoute: typeof AuthenticatedLearnerMyCoursesRoute
  AuthenticatedLearnerSettingsRoute: typeof AuthenticatedLearnerSettingsRoute
  AuthenticatedAdminReviewVersionIdRoute: typeof AuthenticatedAdminReviewVersionIdRoute
  AuthenticatedLearnerCoursesCourseIdRoute: typeof AuthenticatedLearnerCoursesCourseIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedAdminCourseModerationRoute:
    AuthenticatedAdminCourseModerationRoute,
  AuthenticatedAdminDashboardRoute: AuthenticatedAdminDashboardRoute,
  AuthenticatedAdminDiscoverRoute: AuthenticatedAdminDiscoverRoute,
  AuthenticatedAdminFaqRoute: AuthenticatedAdminFaqRoute,
  AuthenticatedAdminGlossaryRoute: AuthenticatedAdminGlossaryRoute,
  AuthenticatedAdminGraphRoute: AuthenticatedAdminGraphRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminUserManagementRoute: AuthenticatedAdminUserManagementRoute,
  AuthenticatedContributorDashboardRoute:
    AuthenticatedContributorDashboardRoute,
  AuthenticatedContributorDiscoverRoute: AuthenticatedContributorDiscoverRoute,
  AuthenticatedContributorFaqRoute: AuthenticatedContributorFaqRoute,
  AuthenticatedContributorGlossaryRoute: AuthenticatedContributorGlossaryRoute,
  AuthenticatedContributorSettingsRoute: AuthenticatedContributorSettingsRoute,
  AuthenticatedContributorTeamsRoute: AuthenticatedContributorTeamsRoute,
  AuthenticatedLearnerDashboardRoute: AuthenticatedLearnerDashboardRoute,
  AuthenticatedLearnerDiscoverRoute: AuthenticatedLearnerDiscoverRoute,
  AuthenticatedLearnerFaqRoute: AuthenticatedLearnerFaqRoute,
  AuthenticatedLearnerGlossaryRoute: AuthenticatedLearnerGlossaryRoute,
  AuthenticatedLearnerMyCoursesRoute: AuthenticatedLearnerMyCoursesRoute,
  AuthenticatedLearnerSettingsRoute: AuthenticatedLearnerSettingsRoute,
  AuthenticatedAdminReviewVersionIdRoute:
    AuthenticatedAdminReviewVersionIdRoute,
  AuthenticatedLearnerCoursesCourseIdRoute:
    AuthenticatedLearnerCoursesCourseIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PreferenceRoute: PreferenceRoute,
  RegisterRoute: RegisterRoute,
  LoginCallbackRoute: LoginCallbackRoute,
  LoginIndexRoute: LoginIndexRoute,
  ContributorTeamIdCoursesRoute: ContributorTeamIdCoursesRoute,
  ContributorEditorCourseIdRoute: ContributorEditorCourseIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
