spring:
  datasource:
    url: jdbc:postgresql://db:5432/postgres
    username: postgres
    password: password

  flyway:
    enabled: true
    locations: classpath:db/migration

  jooq:
    sql-dialect: POSTGRES

  devtools:
    restart:
      enabled: false

  cloud:
    config:
      server:
        awss3:
          region: us-east-1
          bucket: csd-data
          access-key: minioadmin
          secret-key: minioadmin
          endpoint: http://minio:9000
          path-style-access: true

jwt:
  secret: shikanokonokonokokoshitantanshikanokonokonokokoshitantanshikanokonokonokokoshitantan
  # In hours
  access-token:
    expiration: 1
  refresh-token:
    expiration: 720
