name: Deploy Backend to fly

on:
  push:
    branches:
      - dev
      - ci/*

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./backend
    environment: prod
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --config ./.fly/fly.toml --remote-only --build-arg JOOQ_JDBC_URL=${{ secrets.SPRING_DATASOURCE_URL }} --build-arg JOOQ_JDBC_USER=${{ secrets.SPRING_DATASOURCE_USERNAME }} --build-arg JOOQ_JDBC_PASSWORD=${{ secrets.SPRING_DATASOURCE_PASSWORD }}
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_DEPLOY_BACKEND }}
