name: Test Backend

on:
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest
    container: maven:3.9.9-eclipse-temurin-21

    services:
      db:
        image: postgres:18-alpine
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
          POSTGRES_DB: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Flyway
        uses: red-gate/setup-flyway@v1
        with:
          architecture: 'java'

      - name: Run Flyway migrations
        run: |
          flyway migrate \
            -url="jdbc:postgresql://db:5432/postgres" \
            -user=postgres \
            -password=password \
            -locations="filesystem:./backend/src/main/resources/db/migration" \
            -outOfOrder=true

      - name: Run tests with coverage
        env:
          GOOGLE_API_KEY: dummy_key
        run: mvn verify jacoco:report -Djooq.jdbc.url=jdbc:postgresql://db:5432/postgres -Djooq.jdbc.user=postgres -Djooq.jdbc.password=password
        working-directory: ./backend

      - name: Add coverage to PR
        id: jacoco
        uses: madrapps/jacoco-report@v1.7.2
        with:
          paths: ${{ github.workspace }}/backend/target/site/jacoco/jacoco.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          min-coverage-overall: 0
          min-coverage-changed-files: 0
          title: Code Coverage Report
